New

diff --git a/bin/05_Templates/UnitTests/regression_ref_check.gitlab-ci.yml b/bin/05_Templates/UnitTests/regression_ref_check.gitlab-ci.yml
--- a/bin/05_Templates/UnitTests/regression_ref_check.gitlab-ci.yml
+++ b/bin/05_Templates/UnitTests/regression_ref_check.gitlab-ci.yml
@@ -1,262 +1,1 @@
-#!/bin/bash
-
-stages:
-    - Ref_Check
-    - Ref_Update
-   
-
-RegressionTest_Check_References:
-    stage: Ref_Check
-    before_script:
-        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
-        - eval $(ssh-agent -s)
-        - mkdir -p ~/.ssh
-        - ssh-keyscan github.com >> ~/.ssh/known_hosts
-        - ssh-agent -a /tmp/ssh_agent.sock > /dev/null
-        - echo "${GITHUB_PRIVATE_KEY}" > ~/.ssh/id_rsa
-        - chmod 600 ~/.ssh/id_rsa
-        - git config --global user.name "${GITLAB_USER_NAME}" 
-        - git config --global user.email "${GITLAB_USER_EMAIL}"
-        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
-        - export PIP_CACHE_DIR="/opt/cache/pip"
-        - source activate python36  
-        - python -V               # Print out python version for debugging
-        - export PYTHONIOENCODING=utf-8 # just in case
-    script:
-        
-        ## Push new Reference files to Branch
-        - mkdir public
-        - mkdir CorrectedVersion
-        - cd  CorrectedVersion
-        - git clone --single-branch --branch $TARGET_BRANCH git@github.com:${Github_Repository}.git
-        - cd ${CI_PROJECT_NAME}
-        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package AixLib -DS ${DymolaVersion} --tool dymola -n 2 --check-ref -p AixLib < ../bin/06_Configfiles/EOF.sh
-        - cd ..
-        - git ls-files --others --exclude-standard
-        - if cat bin/06_Configfiles/exit.sh | grep "exit 1"; then 
-            rm -r AixLib/funnel_comp ;
-            pushmodel=$(git ls-files --others --exclude-standard);
-            model=$(git diff --raw --diff-filter=AMT HEAD^1);
-            echo $model >  bin/03_WhiteLists/changedmodels.txt;
-            python  bin/02_CITests/CleanUpSkripts/deploy_artifacts.py;
-            message="Automatic push of CI with new regression reference files. Please pull the new files before push again.";
-            git add $pushmodel;
-            git commit -m "$message";
-            git push git@github.com:${Github_Repository}.git;
-            cp $pushmodel Referencefiles;
-            mv Referencefiles/ ../../public/Referencefiles;
-            RED='\033[0;31m';
-            GREEN='\033[0;32m';
-            NC='\033[0m';
-            echo -e "${GREEN}New reference files were pushed to this branch. The job was successfully and the newly added files are tested in another commit.${NC}";
-            exit 0 ;
-          else
-            model=$(git diff --raw --diff-filter=AMT HEAD^1);
-            echo $model >  bin/03_WhiteLists/changedmodels.txt;
-            python  bin/02_CITests/CleanUpSkripts/deploy_artifacts.py;
-            mv Referencefiles/ ../../public/Referencefiles;
-            exit 0 ;
-          fi
-    artifacts:
-        paths:
-            - public
-            - CorrectedVersion/AixLib/AixLib/simulator-dymola.log
-        expire_in: 7 day 
-    except:
-        - IBPSA_Merge
-    except:
-        variables:
-            - $CI_COMMIT_MESSAGE  =~ /Correct HTML Code/
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - give different reference results/
-    only:
-        - external_pull_requests
-    after_script:
-        - cd CorrectedVersion
-        - cd ${CI_PROJECT_NAME}
-        - if cat bin/06_Configfiles/exit.sh | grep "exit 1"; then 
-            curl --request POST --header "PRIVATE-TOKEN:$GL_TOKEN" https://git.rwth-aachen.de/api/v4/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel ;
-            exit 0 ; 
-          else
-            exit 0 ;
-          fi
-
-Airflow_Update_References:
-    stage: Ref_Update
-    before_script:
-        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
-        - export PIP_CACHE_DIR="/opt/cache/pip"
-        - source activate python36  
-        - python -V               # Print out python version for debugging
-        - export PYTHONIOENCODING=utf-8 # just in case
-    script:
-        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package AixLib.Airflow --update-ref -DS ${DymolaVersion} --tool dymola -n 2  < ../bin/06_Configfiles/EOF.sh
-        
-    artifacts:
-        when: on_failure
-        paths:
-            - AixLib/simulator-dymola.log
-            - AixLib/unitTests-dymola.log
-            - AixLib/Resources/ReferenceResults/Dymola
-            - New_Reference_Files
-        expire_in: 7 day 
-    except:
-        - external_pull_requests
-    only:
-        variables:
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
-   
-BoundaryConditions_Update_References:
-    stage: Ref_Update
-    before_script:
-        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
-        - export PIP_CACHE_DIR="/opt/cache/pip"
-        - source activate python36  
-        - python -V               # Print out python version for debugging
-        - export PYTHONIOENCODING=utf-8 # just in case
-    script:
-        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package AixLib.BoundaryConditions --update-ref -DS ${DymolaVersion} --tool dymola -n 2  < ../bin/06_Configfiles/EOF.sh
-        
-    artifacts:
-        when: on_failure
-        paths:
-            - AixLib/simulator-dymola.log
-            - AixLib/unitTests-dymola.log
-            - AixLib/Resources/ReferenceResults/Dymola
-            - New_Reference_Files
-        expire_in: 7 day 
-    except:
-        - external_pull_requests
-    
-    only:
-        variables:
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
-   
-Fluid_Update_References:
-    stage: Ref_Update
-    before_script:
-        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
-        - export PIP_CACHE_DIR="/opt/cache/pip"
-        - source activate python36  
-        - python -V               # Print out python version for debugging
-        - export PYTHONIOENCODING=utf-8 # just in case
-    script:
-        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package AixLib.Fluid --update-ref -DS ${DymolaVersion}  --tool dymola -n 2  < ../bin/06_Configfiles/EOF.sh
-        
-    artifacts:
-        when: on_failure
-        paths:
-            - AixLib/simulator-dymola.log
-            - AixLib/unitTests-dymola.log
-            - AixLib/Resources/ReferenceResults/Dymola
-            - New_Reference_Files
-        expire_in: 7 day 
-    except:
-        - external_pull_requests
-    
-    only:
-        variables:
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
-
-Systems_Update_References:
-    stage: Ref_Update
-    before_script:
-        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
-        - export PIP_CACHE_DIR="/opt/cache/pip"
-        - source activate python36  
-        - python -V               # Print out python version for debugging
-        - export PYTHONIOENCODING=utf-8 # just in case
-    script:
-        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package AixLib.Systems --update-ref -DS ${DymolaVersion} --update-ref --tool dymola -n 2  < ../bin/06_Configfiles/EOF.sh
-        
-    artifacts:
-        when: on_failure
-        paths:
-            - AixLib/simulator-dymola.log
-            - AixLib/unitTests-dymola.log
-            - AixLib/Resources/ReferenceResults/Dymola
-            - New_Reference_Files
-        expire_in: 7 day 
-    except:
-        - external_pull_requests
-    
-    only:
-        variables:
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
-
-ThermalZones _Update_References:
-    stage: Ref_Update
-    before_script:
-        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
-        - export PIP_CACHE_DIR="/opt/cache/pip"
-        - source activate python36  
-        - python -V               # Print out python version for debugging
-        - export PYTHONIOENCODING=utf-8 # just in case
-    script:
-        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package AixLib.ThermalZones --update-ref  -DS ${DymolaVersion} --tool dymola -n 2  < ../bin/06_Configfiles/EOF.sh
-        
-    artifacts:
-        when: on_failure
-        paths:
-            - AixLib/simulator-dymola.log
-            - AixLib/unitTests-dymola.log
-            - AixLib/Resources/ReferenceResults/Dymola
-            - New_Reference_Files
-        expire_in: 7 day 
-    except:
-        - external_pull_requests
-    
-    only:
-        variables:
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
-
-Controls _Update_References:
-    stage: Ref_Update
-    before_script:
-        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
-        - export PIP_CACHE_DIR="/opt/cache/pip"
-        - source activate python36  
-        - python -V               # Print out python version for debugging
-        - export PYTHONIOENCODING=utf-8 # just in case
-    script:
-        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --single-package AixLib.Controls --update-ref  -DS ${DymolaVersion} --tool dymola   < ../bin/06_Configfiles/EOF.sh
-        
-    artifacts:
-        when: on_failure
-        paths:
-            - AixLib/simulator-dymola.log
-            - AixLib/unitTests-dymola.log
-            - AixLib/Resources/ReferenceResults/Dymola
-            - New_Reference_Files
-        expire_in: 7 day 
-    except:
-        - external_pull_requests
-    
-    only:
-        variables:
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
-Media_Update_References:
-    stage: Ref_Update
-    before_script:
-        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
-        - export PIP_CACHE_DIR="/opt/cache/pip"
-        - source activate python36  
-        - python -V               # Print out python version for debugging
-        - export PYTHONIOENCODING=utf-8 # just in case
-    script:
-        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package AixLib.Media --update-ref -DS ${DymolaVersion} --tool dymola -n 2  < ../bin/06_Configfiles/EOF.sh
-        
-    artifacts:
-        when: on_failure
-        paths:
-            - AixLib/simulator-dymola.log
-            - AixLib/unitTests-dymola.log
-            - AixLib/Resources/ReferenceResults/Dymola
-            - New_Reference_Files
-        expire_in: 7 day 
-    except:
-        - external_pull_requests
-    
-    only:
-        variables:
-            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
+#!/bin/bashstages:    - Ref_Check    - Ref_Update      RegressionTest_Check_References:    stage: Ref_Check    before_script:        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'        - eval $(ssh-agent -s)        - mkdir -p ~/.ssh        - ssh-keyscan github.com >> ~/.ssh/known_hosts        - ssh-agent -a /tmp/ssh_agent.sock > /dev/null        - echo "${GITHUB_PRIVATE_KEY}" > ~/.ssh/id_rsa        - chmod 600 ~/.ssh/id_rsa        - git config --global user.name "${GITLAB_USER_NAME}"         - git config --global user.email "${GITLAB_USER_EMAIL}"        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&        - export PIP_CACHE_DIR="/opt/cache/pip"        - source activate python36          - export PYTHONIOENCODING=utf-8 # just in case        - echo 'FAIL' > bin/06_Configfiles/exit2.sh            script:                ## Push new Reference files to Branch        - mkdir public        - mkdir CorrectedVersion        - cd  CorrectedVersion        - git clone --single-branch --branch $TARGET_BRANCH git@github.com:${Github_Repository}.git        - cd ${CI_PROJECT_NAME}        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package AixLib -DS ${DymolaVersion} --tool dymola -n 2 --check-ref -p AixLib < ../bin/06_Configfiles/EOF.sh        - cd ..        - git ls-files --others --exclude-standard        - if cat bin/06_Configfiles/exit.sh | grep "exit 1"; then            rm -r AixLib/funnel_comp ;            pushmodel=$(git ls-files --others --exclude-standard) ;            echo $pushmodel > bin/03_WhiteLists/new_ref.sh ;            model=$(git diff --raw --diff-filter=AMT HEAD^1) ;            echo $model >  bin/03_WhiteLists/changedmodels.txt ;            python  bin/02_CITests/CleanUpSkripts/deploy_artifacts.py ;            message="Automatic push of CI with new regression reference files. Please pull the new files before push again. Plottet Results ${GITLAB_Page}/${TARGET_BRANCH}/plots/AixLib/" ;            git add $pushmodel ;            git commit -m "$message";            git push git@github.com:${Github_Repository}.git ;            cp $pushmodel Referencefiles ;            mv Referencefiles/ ../../public/Referencefiles ;            RED='\033[0;31m' ;            GREEN='\033[0;32m' ;            NC='\033[0m' ;            echo  -e "${GREEN}New reference files were pushed to this branch. The job was successfully and the newly added files are tested in another commit.${NC}" ;            pip install pandas ;            pip install mako ;            pip install matplot ;            python bin/02_CITests/Converter/google_charts.py --line-html --plotModel --ref-txt --single-package AixLib --modellist "$pushmodel" ;            python bin/02_CITests/Converter/google_charts.py  --create-layout ;            pwd ;            cd .. ;            cd .. ;            mkdir -p $CI_COMMIT_REF_NAME/plots ;            cp -r CorrectedVersion/${CI_PROJECT_NAME}/bin/03_WhiteLists/charts/* bin/03_WhiteLists/charts ;            cp -r bin/03_WhiteLists/charts/* $CI_COMMIT_REF_NAME/plots ;            exit 1 ;          else            echo 'successful' > bin/06_Configfiles/exit2.sh ;            model=$(git diff --raw --diff-filter=AMT HEAD^1) ;            echo $model >  bin/03_WhiteLists/changedmodels.txt ;            python  bin/02_CITests/CleanUpSkripts/deploy_artifacts.py ;            mv Referencefiles/ ../../public/Referencefiles ;            exit 0 ;          fi        artifacts:        when: on_failure        paths:            - public            - CorrectedVersion/${CI_PROJECT_NAME}/AixLib/simulator-dymola.log            - CorrectedVersion/${CI_PROJECT_NAME}/bin/03_WhiteLists/charts/AixLib            - bin/03_WhiteLists/charts            - $CI_COMMIT_REF_NAME/plots         expire_in: 7 day     except:        refs:            - IBPSA_Merge        variables:            - $CI_COMMIT_MESSAGE  =~ /Correct HTML Code/            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - give different reference results/    only:        - external_pull_requests
